language: ruby
cache: bundler
rvm:
- 2.2.1
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- bundle exec rubocop
- bundle exec rspec
deploy:
  provider: heroku
  app:
    master: damonzucconi-mesa-production
  api_key:
    secure: I+An9rsESNhcH7eGhnHpsq+ExGJjtWJAXUlXokS8sxQKJ5fg7N21wg1JeiSnMza4qQVydZ3gjgZcoX/LGBx5mKaLXwY7lTaU4uTlSaI45Ikncj3mkL7pXjoWvZBcckNxgRMyDCYze4Q9E6fpj6PaRwL2hD5LWghuWcdHe9DG1VY=
  run: 'rake db:migrate'
